import { NextResponse } from "next/server";
import { requireCurrentUser } from "@/lib/auth";
import { ensureCurrentMatchForUser, getCurrentMatchForUser } from "@/lib/match-service";

export async function GET() {
  try {
    const user = await requireCurrentUser();
    const result = await getCurrentMatchForUser(user.id);
    return NextResponse.json({ ok: true, autoGenerated: false, ...result });
  } catch (error) {
    const code = error instanceof Error ? error.message : "UNKNOWN_ERROR";
    if (code === "UNAUTHORIZED") {
      return NextResponse.json({ ok: false, error: code }, { status: 401 });
    }
    return NextResponse.json({ ok: false, error: code }, { status: 500 });
  }
}

export async function POST() {
  try {
    const user = await requireCurrentUser();
    const before = await getCurrentMatchForUser(user.id);
    const result = await ensureCurrentMatchForUser(user.id);
    return NextResponse.json({
      ok: true,
      autoGenerated: !before?.match && Boolean(result?.match),
      ...result,
    });
  } catch (error) {
    const code = error instanceof Error ? error.message : "UNKNOWN_ERROR";
    if (code === "UNAUTHORIZED") {
      return NextResponse.json({ ok: false, error: code }, { status: 401 });
    }
    return NextResponse.json({ ok: false, error: code }, { status: 500 });
  }
}
